name: dev.hyyperb.pythonrunner
version: 1.0.7
main: pythonrunner.CorePlugin
api-version: 1.19.2

commands:
  runpy:
    description: Run the python code inside written your book
    usage: /<command>
    permission: pythonrunner.commands.CommandRunPy

  graphpy:
    discription: Plot a graph from python code by printing out coords in format x,y,z seperated by \n
    usage: /<command>
    permission: pythonrunner.commands.CommandGraphPy

